#use ELECTRONICA_DW;
#select * from Customer;
#select * from SALES;
#select * from Store;
#select * from Product;
#select * from Supplier;
#select * from Time;
#select * from Sales;
use ELECTRONICA_DW; 

# Q1: 

SELECT 
    Supplier.SUPPLIER_ID,
    Time.YEAR,
    Time.QUARTER,
    Time.MONTH,
    SUM(Sales.TOTAL_SALE) AS TOTAL_SALES
FROM 
    ELECTRONICA_DW.Sales
JOIN 
    ELECTRONICA_DW.Time ON Sales.TIME_ID = Time.TIME_ID
JOIN 
    ELECTRONICA_DW.Supplier ON Sales.SUPPLIER_ID = Supplier.SUPPLIER_ID
GROUP BY 
    Supplier.SUPPLIER_ID, Time.YEAR, Time.QUARTER, Time.MONTH
ORDER BY 
    Supplier.SUPPLIER_ID, Time.YEAR, Time.QUARTER, Time.MONTH;

# Q2

SELECT 
    Product.PRODUCT_ID,
    Time.MONTH,
    SUM(Sales.TOTAL_SALE) AS TOTAL_SALES
FROM 
    ELECTRONICA_DW.Sales
JOIN 
    ELECTRONICA_DW.Time ON Sales.TIME_ID = Time.TIME_ID
JOIN 
    ELECTRONICA_DW.Product ON Sales.PRODUCT_ID = Product.PRODUCT_ID
JOIN 
    ELECTRONICA_DW.Supplier ON Sales.SUPPLIER_ID = Supplier.SUPPLIER_ID
WHERE 
    (Supplier.SUPPLIER_NAME = 'DJI' OR Supplier.SUPPLIER_NAME IS NULL) AND Time.YEAR = 2019
GROUP BY 
    Product.PRODUCT_ID, Time.MONTH
WITH ROLLUP
ORDER BY 
    Product.PRODUCT_ID, Time.MONTH;

# Q3

SELECT 
    Product.PRODUCT_ID,
    Product.PRODUCT_NAME,
    SUM(Sales.QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM 
    ELECTRONICA_DW.Sales
JOIN 
    ELECTRONICA_DW.Time ON Sales.TIME_ID = Time.TIME_ID
JOIN 
    ELECTRONICA_DW.Product ON Sales.PRODUCT_ID = Product.PRODUCT_ID
WHERE 
    Time.DAY_OF_WEEK IN ('Saturday', 'Sunday')
GROUP BY 
    Product.PRODUCT_ID, Product.PRODUCT_NAME
ORDER BY 
    TOTAL_QUANTITY_SOLD DESC
LIMIT 5;

# Q4

SELECT 
    Product.PRODUCT_ID,
    Product.PRODUCT_NAME,
    SUM(CASE WHEN Time.QUARTER = 1 THEN Sales.TOTAL_SALE ELSE 0 END) AS Q1_Sales,
    SUM(CASE WHEN Time.QUARTER = 2 THEN Sales.TOTAL_SALE ELSE 0 END) AS Q2_Sales,
    SUM(CASE WHEN Time.QUARTER = 3 THEN Sales.TOTAL_SALE ELSE 0 END) AS Q3_Sales,
    SUM(CASE WHEN Time.QUARTER = 4 THEN Sales.TOTAL_SALE ELSE 0 END) AS Q4_Sales,
    SUM(Sales.TOTAL_SALE) AS Total_Yearly_Sales
FROM 
    ELECTRONICA_DW.Sales
JOIN 
    ELECTRONICA_DW.Time ON Sales.TIME_ID = Time.TIME_ID
JOIN 
    ELECTRONICA_DW.Product ON Sales.PRODUCT_ID = Product.PRODUCT_ID
WHERE 
    Time.YEAR = 2019
GROUP BY 
    Product.PRODUCT_ID, Product.PRODUCT_NAME
ORDER BY 
    Product.PRODUCT_ID;

# Q5

SELECT 
    Store.STORE_ID,
    Store.STORE_NAME,
    Supplier.SUPPLIER_ID,
    Supplier.SUPPLIER_NAME
FROM 
    ELECTRONICA_DW.Store
JOIN 
    ELECTRONICA_DW.Supplier ON Store.STORE_NAME = Supplier.SUPPLIER_NAME
WHERE 
    Store.STORE_NAME = 'Pakistan' AND Supplier.SUPPLIER_NAME = 'Pakistan';

# Q6

DROP VIEW IF EXISTS STOREANALYSIS_MV;
CREATE VIEW STOREANALYSIS_MV AS
SELECT 
    Sales.STORE_ID,
    Sales.PRODUCT_ID AS PROD_ID,
    SUM(Sales.TOTAL_SALE) AS STORE_TOTAL
FROM 
    ELECTRONICA_DW.Sales
GROUP BY 
    Sales.STORE_ID, Sales.PRODUCT_ID;

SELECT * FROM STOREANALYSIS_MV;

#Q7 

SELECT 
    Time.MONTH,
    Product.PRODUCT_ID,
    Product.PRODUCT_NAME,
    SUM(Sales.TOTAL_SALE) AS TOTAL_SALES
FROM 
    ELECTRONICA_DW.Sales
JOIN 
    ELECTRONICA_DW.Time ON Sales.TIME_ID = Time.TIME_ID
JOIN 
    ELECTRONICA_DW.Product ON Sales.PRODUCT_ID = Product.PRODUCT_ID
JOIN 
    ELECTRONICA_DW.Store ON Sales.STORE_ID = Store.STORE_ID
WHERE 
    Store.STORE_NAME = 'Tech Haven'
GROUP BY 
    Time.MONTH, Product.PRODUCT_ID, Product.PRODUCT_NAME
ORDER BY 
    Time.MONTH, Product.PRODUCT_ID;

# Q8

DROP VIEW IF EXISTS SUPPLIER_PERFORMANCE_MV;
CREATE VIEW SUPPLIER_PERFORMANCE_MV AS
SELECT 
    Supplier.SUPPLIER_ID,
    Supplier.SUPPLIER_NAME,
    Time.YEAR,
    Time.MONTH,
    SUM(Sales.TOTAL_SALE) AS MONTHLY_SALES
FROM 
    ELECTRONICA_DW.Sales
JOIN 
    ELECTRONICA_DW.Time ON Sales.TIME_ID = Time.TIME_ID
JOIN 
    ELECTRONICA_DW.Supplier ON Sales.SUPPLIER_ID = Supplier.SUPPLIER_ID
GROUP BY 
    Supplier.SUPPLIER_ID, Supplier.SUPPLIER_NAME, Time.YEAR, Time.MONTH;
SELECT * FROM SUPPLIER_PERFORMANCE_MV;

# Q9

SELECT 
    Sales.CUSTOMER_ID,
    COUNT(DISTINCT Sales.PRODUCT_ID) AS UNIQUE_PRODUCTS_PURCHASED,
    SUM(Sales.TOTAL_SALE) AS TOTAL_SALES
FROM 
    ELECTRONICA_DW.Sales
JOIN 
    ELECTRONICA_DW.Time ON Sales.TIME_ID = Time.TIME_ID
WHERE 
    Time.YEAR = 2019
GROUP BY 
    Sales.CUSTOMER_ID
ORDER BY 
    TOTAL_SALES DESC, UNIQUE_PRODUCTS_PURCHASED DESC
LIMIT 5;

# Q10

DROP VIEW IF EXISTS CUSTOMER_STORE_SALES_MV;
CREATE VIEW CUSTOMER_STORE_SALES_MV AS
SELECT 
    Sales.STORE_ID,
    Store.STORE_NAME,
    Sales.CUSTOMER_ID,
    Time.YEAR,
    Time.MONTH,
    SUM(Sales.TOTAL_SALE) AS MONTHLY_SALES
FROM 
    ELECTRONICA_DW.Sales
JOIN 
    ELECTRONICA_DW.Time ON Sales.TIME_ID = Time.TIME_ID
JOIN 
    ELECTRONICA_DW.Store ON Sales.STORE_ID = Store.STORE_ID
GROUP BY 
    Sales.STORE_ID, Store.STORE_NAME, Sales.CUSTOMER_ID, Time.YEAR, Time.MONTH;
SELECT * FROM CUSTOMER_STORE_SALES_MV;

